ONSdigital/dp-data-tools

- mongo-fixes/download-structure/README.md
- mongo-fixes/download-structure/mian.go
- Add a download structure script
> Add a script to update the download structure

- check-audit/main.go
Previously attempted actions falling into unsuccessful
> Represent Action attempted in check-audit utility

- README.md
- mongo-fixes/neptune-migration/README.md
- mongo-fixes/neptune-migration/neptune-migration.sh
- mongo-fixes/neptune-migration/recipes.json
- mongo-fixes/neptune-migration/remove-backups/remove-neo4j-backups.sh
- mongo-fixes/neptune-migration/restore-neo4j/restore-neo4j.sh
Add script to reset MongoDB data for the Neptune migration
- Remove all documents from all collections
- Import the recipes defined in `recipes.json`
Sanity check
anyone
> Add script to reset MongoDB data for the Neptune migration

- mongo-fixes/neptune-migration/recipes.json
Update the recipe import data
- updates as given by the data team
> Update the recipe import data

- kafka-tools/check-audit/go.mod
Module was missing kafka-tools in path
> Fix module path for kafka-tools/kafka-audit

- topics-tools/gen-topics-database/main.go
Minor addition to gather information to feed into design of dp-topics-api:
Sum up and print out 'maxContentItems'
> Sum up and print out 'maxContentItems'

- audit-tools/ons-audit-uri/main.go
1. Ran golangci-lint and fixed nearly all issues
Used command:
golangci-lint --deadline=10m --fast --enable=gosec --enable=gocritic --enable=gofmt --enable=gocyclo --enable=bodyclose --enable=gocognit run
2. Big refactor. Fix bug for DeepEqual check. Add 'paginator' struct.
3. Pass and access some large json lines around via pointers, add comment.
4. Replace `if` chain with switch
5. Add more fields to struct: resultDescription
> Refactor after lint check, bug fix and clean up.

- audit-tools/ons-audit-uri/main.go
Visual inspection will suffice.
> Add new AroundONS field to HomePageResponse

- kafka-tools/drain-topic/Makefile
- kafka-tools/drain-topic/scripts/ensure_vars
i.e. needs go-style vars, not java vars
> update drain-topic: accomodate draining a topic for a java app

- kafka-tools/drain-topic/README.md
Documentation has been updated to further clarify how to drain a kafka topic.
These changes also fix the problem of the dollar sign being copied when the commands are copied from the git UI.
Check that the documentation looks correct.
Anyone but me
> Fix kafka drain instructions

- README.md
- mongo-fixes/update-topic-ids/README.md
- mongo-fixes/update-topic-ids/update-topic-ids.js
Add a new script to update all topics with a new nano id
> Add script to update topic ids

- kafka-tools/generate-downloads/README.md
> Add section 'Getting the `INSTANCE_ID`, a worked example'

- dp-identity-data-migration/groupsdataextraction/group_extraction.go
Rename col in groups export to match backup script
> Rename col in groups export to match backup script

- .gitignore
- dp-identity-data-migration/groupsdataextraction/README.md
- dp-identity-data-migration/groupsdataextraction/group_extraction.go
- dp-identity-data-migration/userdataextraction/README.md
- dp-identity-data-migration/userdataextraction/go.mod
- dp-identity-data-migration/userdataextraction/go.sum
- dp-identity-data-migration/userdataextraction/user_extraction.go
Bugs:-
user groups file not containing team reference
groups/team key to reflect key from zebedee (so that collection teams would still work)
code follow current standards 
test run scripts and check files in s3
anyone but me
> usergroups key fix groups key fix for collections

- dp-identity-data-migration/groupsdataextraction/README.md
- dp-identity-data-migration/userdataextraction/README.md
Added warning about validusers env var.
Check ok and makes sense. 
Not me.
> Add more specificity to validusers env var

- mongo-tools/delete-collection/Makefile
- mongo-tools/delete-collection/README.md
- mongo-tools/delete-collection/delete-collection.js
Add script and readme guide for deleting a documentdb collection
Trello - https://trello.com/c/vE6Ut8K3/1917-remove-interactives-collection-from-documentdb
Confirm changes are correct/make sense
Anyone
> add script for deleting a docdb collection

- find-content-items/find_content_items.go
Add `data_cy.json` filetype to script (forgot to add it initially)
Confirm above has been added
Anyone
> add missing data_cy.json filetype

- audit-tools/manifest-check/manifest-check.go
As per title.
Visual inspection.
Anyone.
> Add handling of 'docker-deploy' Type

- audit-tools/ami-check/1-get-ami-info.sh
- audit-tools/ami-check/get-ami-info/process-ami-json.go
Ensure working directories exist by creating them.
Visual inspection.
Anyone.
> Add creation of needed working directories

- .github/CODEOWNERS
Modified CODEOWNERS file to only apply to .github directory
> Modify CODEOWNERS file to .github only

- README.md
- zebedee-content-tools/publishing-timings/.gitignore
- zebedee-content-tools/publishing-timings/Makefile
- zebedee-content-tools/publishing-timings/README.md
- zebedee-content-tools/publishing-timings/go.mod
- zebedee-content-tools/publishing-timings/main.go
Added a tool for analysing timings of published collections/releases
Look at code, give it a go, etc.
Anyone but me
> Add publishing-timings tool

- zebedee-content-tools/publishing-timings/main.go
Fix issues with the publishing-timings tool
- Local time / London time mismatch on AWS
- PubSector finances added to release description guesser
Sanity check
Anyone but me
> Fix timezone issues in publishing-timings

- zebedee-content-tools/publishing-timings/main.go
Limit publish-timings pre-pub end time calc to pre-pub uris. This reads the manifest files to find out which uris are sent over on pre-publish then only uses the transaction creation times of those when calculating pre-publish end time. This is because non pre-publish uris will be created at publish time instead and create false results. 
Appraise the code
Anyone
> Limit publish-timings pre-pub end time calc to pre-pub uris

- audit-tools/manifest-check/manifest-check.go
As per title
Visual inspection, run tool as per instructions in readme.
Anyone.
> Update for recent new manifest types
